### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by Orv** [aredn/aredn_ar71xx#158]
Add note to beginning of page at https://www.arednmesh.org/content/uploading-firmware-ubiquiti
NOTE: If uploading nightly build firmware to a Ubiquiti device, downgrading AirOS is NOT required.

Add note to beginning of page at https://www.arednmesh.org/content/software:
NOTE: If uploading nightly build firmware to a Ubiquiti device, running the U-Boot Test Program is NOT required.

**Comment by wu2s** [comment]
Updated the web page: "Current AREDN nightly builds can be loaded onto any supported (or ‘in testing’) Ubiquiti device by using the TFTP method.   If the version of AirOS is v5.5 or lower, then the AirOS Web Interface may be used to load AREDN.   The bootloader provided with AirOS 5.6 and higher will check for official “signed Ubiquiti firmware” before loading via the AirOS Web Interface.  Since AREDN firmware is not signed by Ubiquiti, this will fail.  However, TFTP should continue to work."
