### ISSUE TITLE
WiFi Scan

### ISSUE THREAD

**Issue by ZL2ARN** [aredn/aredn_ar71xx#337]
Firmware 3.16.1.0 provided free access to WIFI scans on the Mesh Nodes.
All later versions now require "password" access to see the scan list.
My memory is a little poor on why this was changed. Was it for security reasons. ??
We have an extensive WIFI Network here in Wellington ZL, and it is vital to use the WiFi Scan at each Node to check for adjacent activity, and to prevent any Channel clashes.
Would it be possible to re-instate **no password** access again ??

**Comment by ae6xe** [comment]
The wifi scan will trigger RF emissions on all the channels.   On 5GHz this would include DFS channels where you might have primary doppler radar in your area.  With abundance of caution, the password ensures that only the node owner or trusted users can control the emissions.

**Comment by ZL2ARN** [comment]
Hi Joe,
Thanks for your reply.
“A client can use two scanning methods: **active** and **passive**. During an active scan, the client radio transmits a probe request and listens for a probe response from an AP. With a passive scan, the client radio listens on each channel for beacons sent periodically by an AP.”
Can you confirm it is an **active scan** in the Mesh Nodes ?? 
The speed of reply would suggest it is an active scan. A passive scan would I think take much longer waiting for the periodical beacons to occur.

**Comment by ZL2ARN** [comment]
Thanks Joe,
I have very carefully edited  ../bin/wscan in the two locations as you detailed. Then rebooted just to ensure no scan data was saved in memory.
First impressions are that nothing has changed and WIFI scan results are just the same.
So will now locate a Spectrum analyser to observe (RF) both active and passive scans.
My test node is just a few feet away from the work station so will be able to see any active scans.

**Comment by ae6xe** [comment]
With a specturm analyser, the ms blip of energy wouldn't be noticeable.     The way I'd do this is capture packets on the neighbor node, then review the traffic to see what was transmitted or not.  To do this, install the "tcpdump-mini" package (you may have to load the current nightly build to do so, given signatures on the packages).  

Run this command, "tcpdump -i wlan0-1 -c 1000 -w /tmp/scan.pcap"

This will grab 1000 packets, then stop.   Thus, trigger a few scans in that time period.  This file is then copied to a laptop with scp, and open up with wireshark or send to me to review.  (before and after captures.)   wireshark can filter the packets on management frames, beacons, etc. to find what we're looking to see or not see.   Put the device settings on 20MHz channel width to ensure unlicensed wifi in the area is showing up.   wifi scan only shows devices on the same channel bandwidth.

Note, showing mesh nodes on same channel and ssid is a different command and does not require any emissions to show in list, because we already have a connection to them and know that list.  It's all the other possible entries that are the focus.  Ideal environment is if there are 10 to 20 neighbor home wifi signals showing up.

**Comment by ZL2ARN** [comment]
I have set up two local nodes, one as the tcpdump, and the other as the WIFI Scan node.
Both can see a good selection of MESH and "other" nodes.
Final check now before I proceed. I have found two entries in...../local/bin/wscan, line 171 is straight forward and simple to modify as detailed above. Is line 182 the second line to modify ?? it is the only other one I can find. I have inserted "passive" directly after "scan" and left everything else as is on this line. ??
I shall now try my first tcpdump and see how I get on.

**Comment by ae6xe** [comment]
Yes, the line numbers sound right.    I did a comparison at my QTH with 20+ SSIDs in range.   I found both active and passive scans took multiple tries to see all SSIDs.  I did not distinguish any difference with the passive scan of significance, instead of a scan 2 to 3 times to see all SSIDs, it might be 3 to 4 times.

**Comment by ZL2TB** [comment]
An observation
Tried a WIFI scan from my node (NSM2 XM up high in suburbia)  with it running both full power and also minimum power output. Same selection of WIFI's reported regardless . Was a little surprised to see this as I would have expected at low power some external and weaker WIFI's would not hear my "probe"
Rgds tedl in NZ

**Comment by ZL2ARN** [comment]
scan.pcap files attached.
1. scan1.pcap passive, WIFI Scan continuous
2. scan2.pcap passive, NO WIFI scan
3. scan3.pcap (passive removed) active, WIFI Scan continuous
4. scan4.pcap (passive removed) active, NO WIFI scan
Wireshark display looks interesting, so will study here also in detail.
[scan.pcap.zip](https://github.com/aredn/aredn_ar71xx/files/2850264/scan.pcap.zip)

**Comment by ae6xe** [comment]
Would it be possible to do the scan and the tcpdump on the same device?   This should show the transmitted probes on each of the channels.    when the tcpdump is captured on another node, listening only on one channel, we don't see what frequencies are being scanned-probed.   

I ran into another forum discussion where someone stated the DFS 5GHz channels disable active scans, per the 802.11 spec.    AREDN changed the wireless regulatory database such that our country code channels do not have DFS labels.  thus AREDN scans probably probe DFS channels.

I'm back at SoCal QTH on the 18th, in a week, will have to do some testing and also reproduce on 5GHz.

**Comment by ZL2ARN** [comment]
Scan and dump on CPEv3 only.
1. pcap.png  showing an example of the standard WIFI Scan results.
2. scan.pcap dump (passive removed) active.
3. scan1.pcap dump passive .
[pcap.zip](https://github.com/aredn/aredn_ar71xx/files/2892897/pcap.zip)
WIFI Scan was in auto mode for these tests. (About 3 scans in the time frame)

**Comment by ae6xe** [comment]
No password scan was restored with:

https://github.com/aredn/aredn_ar71xx/commit/3a4d92add23e59851cf8e694ae7f3ce0f776206d
